export const events = [
  {
    title: "applicationCommandPermissionsUpdate",
    value: "applicationCommandPermissionsUpdate",
  },
  { title: "channelCreate", value: "channelCreate" },
  { title: "channelDelete", value: "channelDelete" },
  { title: "channelPinsUpdate", value: "channelPinsUpdate" },
  { title: "channelUpdate", value: "channelUpdate" },
  { title: "debug", value: "debug" },
  { title: "emojiCreate", value: "emojiCreate" },
  { title: "emojiDelete", value: "emojiDelete" },
  { title: "emojiUpdate", value: "emojiUpdate" },
  { title: "error", value: "error" },
  { title: "guildBanAdd", value: "guildBanAdd" },
  { title: "guildBanRemove", value: "guildBanRemove" },
  { title: "guildCreate", value: "guildCreate" },
  { title: "guildDelete", value: "guildDelete" },
  { title: "guildIntegrationsUpdate", value: "guildIntegrationsUpdate" },
  { title: "guildMemberAdd", value: "guildMemberAdd" },
  { title: "guildMemberAvailable", value: "guildMemberAvailable" },
  { title: "guildMemberRemove", value: "guildMemberRemove" },
  { title: "guildMembersChunk", value: "guildMembersChunk" },
  { title: "guildMemberUpdate", value: "guildMemberUpdate" },
  { title: "guildScheduledEventCreate", value: "guildScheduledEventCreate" },
  { title: "guildScheduledEventDelete", value: "guildScheduledEventDelete" },
  { title: "guildScheduledEventUpdate", value: "guildScheduledEventUpdate" },
  { title: "guildScheduledEventUserAdd", value: "guildScheduledEventUserAdd" },
  {
    title: "guildScheduledEventUserRemove",
    value: "guildScheduledEventUserRemove",
  },
  { title: "guildUnavailable", value: "guildUnavailable" },
  { title: "guildUpdate", value: "guildUpdate" },
  { title: "interactionCreate", value: "interactionCreate" },
  { title: "invalidated", value: "invalidated" },
  { title: "inviteCreate", value: "inviteCreate" },
  { title: "inviteDelete", value: "inviteDelete" },
  { title: "messageCreate", value: "messageCreate" },
  { title: "messageDelete", value: "messageDelete" },
  { title: "messageDeleteBulk", value: "messageDeleteBulk" },
  { title: "messageReactionAdd", value: "messageReactionAdd" },
  { title: "messageReactionRemove", value: "messageReactionRemove" },
  { title: "messageReactionRemoveAll", value: "messageReactionRemoveAll" },
  { title: "messageReactionRemoveEmoji", value: "messageReactionRemoveEmoji" },
  { title: "messageUpdate", value: "messageUpdate" },
  { title: "presenceUpdate", value: "presenceUpdate" },
  { title: "ready", value: "ready" },
  { title: "roleCreate", value: "roleCreate" },
  { title: "roleDelete", value: "roleDelete" },
  { title: "roleUpdate", value: "roleUpdate" },
  { title: "shardDisconnect", value: "shardDisconnect" },
  { title: "shardError", value: "shardError" },
  { title: "shardReady", value: "shardReady" },
  { title: "shardReconnecting", value: "shardReconnecting" },
  { title: "shardResume", value: "shardResume" },
  { title: "stageInstanceCreate", value: "stageInstanceCreate" },
  { title: "stageInstanceDelete", value: "stageInstanceDelete" },
  { title: "stageInstanceUpdate", value: "stageInstanceUpdate" },
  { title: "stickerCreate", value: "stickerCreate" },
  { title: "stickerDelete", value: "stickerDelete" },
  { title: "stickerUpdate", value: "stickerUpdate" },
  { title: "threadCreate", value: "threadCreate" },
  { title: "threadDelete", value: "threadDelete" },
  { title: "threadListSync", value: "threadListSync" },
  { title: "threadMembersUpdate", value: "threadMembersUpdate" },
  { title: "threadMemberUpdate", value: "threadMemberUpdate" },
  { title: "threadUpdate", value: "threadUpdate" },
  { title: "typingStart", value: "typingStart" },
  { title: "userUpdate", value: "userUpdate" },
  { title: "voiceStateUpdate", value: "voiceStateUpdate" },
  { title: "warn", value: "warn" },
  { title: "webhookUpdate", value: "webhookUpdate" },
];
